name: Static Code Checks
on: [push]

jobs:
  quality:
    name: Static Code Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: ./.github/actions/setup-poetry-env

      - name: Check Packages
        run: make check-packages

      - name: Check Security
        run: make check-security

      - name: Check Code
        run: make check-code