name: Static Code Checks
on: [push]

jobs:
  quality:
    name: Static Code Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Check Poetry lock file consistency
        run: poetry lock --check

      - run: poetry --version
